### PR TITLE
add option to disable fallback

### LINKED ISSUE #116: make using PDO fallback optional
ref: https://keboola.slack.com/archives/C035LGNK5/p1558694535000900

### PR DESCRIPTION
**Pull request by pivnicek**
Fixes #116 

One thing that I don't like about this is that BCP is not retried.

### CODE REVIEW

**Comment by MiroCillik** [comment]
Why it is not retried?

**Comment by pivnicek** [comment]
Thanks @MiroCillik .  ugh
> Adding a simple test that the PDO fallback didn't happen shouldn't be too hard.
There are 2 new tests there that do exactly this, did you miss them?

**Comment by pivnicek** [comment]
lol, sorry miro!  I'd forgotten to commit them 🤦‍♂ !   Pushed now, thanks

**Comment by pivnicek** [comment]
> Adding this option has nothing to do with retries or?

Well, there's no retry wrapper on the BCP, it retries the fallback if that fails.  Not sure if it should maybe be for another issue/PR though.  Curious to @tomasfejfar thoughts.

**Comment by tomasfejfar** [comment]
I think we really need to cleanup the "main loop" first - extract and isolate the BCP and PDO into their own classes or at least methods. BCP has it's own class, but only for the extraction itself. There is ton of other code in the try/catch block still. 

I may try to do it, if you want... 

image

**Comment by MiroCillik** [comment]
@pivnicek lol, I just looked at it and thought that I must've been blind yesterday :D 
OK it's fine with the tests. Tomas is right about cleaning "the main loop" a little bit.

**Comment by pivnicek** [comment]
Yeah @tomasfejfar I agree about the cleanup (give it a go by all means! :) ).  But I think it should be in a different PR.

**Comment by tomasfejfar** [comment]
Certainly in different PR.

**Pull request merged**
